config/routes.rb
Rails.application.routes.draw do
  resources :events do
    resources :tasks
  end

  root to: "events#index"

end

app/models/event.rb
class Event < ActiveRecord::Base
	has_many :tasks
	validates :title, :presence => true

	accepts_nested_attributes_for :tasks, :allow_destroy => true, :reject_if => :all_blank, :update_only => true
end

app/models/task.rb
class Task < ActiveRecord::Base
	belongs_to :event

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @event = Event.find(params[:id])
    @task = @event.tasks.all
  end

  # GET /events/new
  def new
    @event = Event.new
    @task = @event.tasks.build
  end

  # GET /events/1/edit
  def edit
    @event = Event.find(params[:id])
    @task = @event.tasks.new
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to events_path, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:title, :content, :date, :tasks_attributes => [:id, :content, :due, :_destroy])
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

	def show
		@task = Task.find(params[:id])
	end

	def destroy
		@task = Task.find(params[:id])
		@task.destroy
		redirect_to :back
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/events/_form.html.erb
<div class="nested_form">
<%= nested_form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <p>事件標題：</p>
    <%= f.text_field :title %>
    <p>日期：</p>
    <%= f.text_field :date %>
  </div>
<hr/>
  <%= f.fields_for :tasks do |t| %>
    <h4>新待辦事項：</h4>
    <p>內容：<%= t.text_field :content %></p>
    <p>截止時間：<%= t.text_field :due %></p>
    <p><%= t.link_to_remove "移除此待辦事項" %></p>
    <hr/>
  <% end %>
    <p><%= f.link_to_add "新增待辦事項", :tasks %></p>

  <div class="actions">
    <%= f.submit "確認", class: "button tiny" %>
  </div>
<% end %>
</div>

app/views/events/edit.html.erb
<h1>修改事件</h1>

<%= render 'form' %>

<%= link_to '取消', :back %>

app/views/events/index.html.erb
<p></p>
<%= link_to '新增事件', new_event_path, :class => "button", :style => "color: white" %>
<hr/>
<p style="font-size:20px">所有事件</p>
<table class="table talbe-bordered">
  <thead>
    <tr>
      <th style="width:200px;">事件</th>
      <th style="width:200px;">待辦事項數量</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr class="admin">
        <td><%=link_to event.title, event_path(event) %></td>
        <td><%= event.tasks.count %></td>
        <td><%= link_to '刪除', event, method: :delete, data: { confirm: '確定嗎？' }, :class => "delete" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/events/new.html.erb
<h1>新的事件</h1>

<%= render 'form' %>

<%= link_to '取消', events_path %>

app/views/events/show.html.erb
<h3><%= @event.title %></h3>
<p><strong>內容:</strong><%= @event.content %></p>
<p><strong>日期:</strong><%= @event.date %></p>
<hr/>

<% i = 1 %>
<% @task.each do |t| %>
	<div class="admin">
		<h4>待辦事項 <%= i %><span class="delete">&nbsp;<%= link_to "刪除", event_task_path(@event, t), method: :delete, :style => "color: blue" %></span></h4>
		<p>內容：<%= t.content %></p>
		<p>截止日期：<%= t.due %></p>

		<% i = i + 1 %>
	</div>
<% end %>

<%= link_to '編輯', edit_event_path(@event), :class => "button tiny", :style => "color:white" %>&nbsp;<%= link_to '回到首頁', events_path, :class => "button tiny", :style => "color:white" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NestedForm</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
<%= yield %>
</div>
</body>
</html>